#!/usr/bin/env bash

# This file is generated by scripts/build_bashrc_common.sh.
# Do not edit it directly; edit files under src/ instead.


# Development entrypoint. The build script expands the source lines below
# into a single distributable bashrc_common.sh artifact.

# Shared dotfile paths, URLs, and install-time defaults.
DOTFILES_DIR="$HOME/.dotfile"
COMMON_FILE="$DOTFILES_DIR/bashrc_common.sh"
DOTFILE_RAW_COMMON_URL="https://raw.githubusercontent.com/panjd123/dotfile/master/bashrc_common.sh"
DOTFILE_NETWORK_REGION_FILE="$DOTFILES_DIR/.network_region"
DOTFILE_CN_PYPI_INDEX="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
DOTFILE_CN_PYPI_HOST="mirrors.tuna.tsinghua.edu.cn"
DOTFILE_CN_HF_ENDPOINT="https://hf-mirror.com"
DOTFILE_AUTHORIZED_KEYS_FILE="$HOME/.ssh/authorized_keys"
DOTFILE_SSHD_CONFIG_FILE="/etc/ssh/sshd_config"

DOTFILE_SSH_PUBLIC_KEYS=(
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG3Mt/bijvkMa15XthVwRu1BHH/WE66IaiYXyQonN6RX 1747366367@qq.com"
)

DOTFILE_SSH_CONFIG_CHECKS=(
  "PubkeyAuthentication yes"
)

declare -A DOTFILE_DEFAULT_SSH_VALUES
DOTFILE_DEFAULT_SSH_VALUES["PubkeyAuthentication"]="yes"
DOTFILE_DEFAULT_SSH_VALUES["PasswordAuthentication"]="yes"
DOTFILE_DEFAULT_SSH_VALUES["PermitRootLogin"]="prohibit-password"

declare -a DOTFILE_INSTALL_PLAN_SSH_CONFIG=()
declare -a DOTFILE_INSTALL_PLAN_SSH_KEYS=()
# Region detection and region-gated mirror environment variables.
dotfile_read_network_region() {
  if [ ! -f "$DOTFILE_NETWORK_REGION_FILE" ]; then
    echo "UNKNOWN"
    return 0
  fi

  head -n 1 "$DOTFILE_NETWORK_REGION_FILE" 2>/dev/null | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]'
}

dotfile_write_network_region() {
  local region="${1:-UNKNOWN}"
  mkdir -p "$DOTFILES_DIR"
  printf '%s\n' "$region" > "$DOTFILE_NETWORK_REGION_FILE"
}

dotfile_detect_network_region() {
  local country_code=""
  local response=""
  local url=""
  local -a country_code_urls=(
    "https://ipinfo.io/country"
    "https://ifconfig.co/country-iso"
    "https://ipapi.co/country/"
  )

  if ! command -v curl >/dev/null 2>&1; then
    echo "UNKNOWN"
    return 0
  fi

  # Try lightweight country-code endpoints first, then fall back to a page that
  # can still hint whether the machine is in mainland China.
  for url in "${country_code_urls[@]}"; do
    response=$(curl -fsSL --connect-timeout 2 --max-time 5 "$url" 2>/dev/null || true)
    country_code=$(printf '%s' "$response" | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
    if [[ "$country_code" =~ ^[A-Z]{2}$ ]]; then
      break
    fi
  done

  if [[ ! "$country_code" =~ ^[A-Z]{2}$ ]]; then
    response=$(curl -fsSL --connect-timeout 2 --max-time 5 "https://cip.cc" 2>/dev/null || true)
    if printf '%s' "$response" | grep -Eiq '中国|china'; then
      country_code="CN"
    elif [ -n "$response" ]; then
      country_code="NON_CN"
    fi
  fi

  if [ "$country_code" = "CN" ]; then
    echo "CN"
  elif [[ "$country_code" =~ ^[A-Z]{2}$ ]] || [ "$country_code" = "NON_CN" ]; then
    echo "OVERSEAS"
  else
    echo "UNKNOWN"
  fi
}

dotfile_refresh_network_region() {
  local region
  region=$(dotfile_detect_network_region)
  dotfile_write_network_region "$region"
  echo "[dotfile] 当前网络区域: $region"
}

dotfile_apply_cn_network_settings() {
  export UV_DEFAULT_INDEX="$DOTFILE_CN_PYPI_INDEX"
  export PIP_INDEX_URL="$DOTFILE_CN_PYPI_INDEX"
  export PIP_TRUSTED_HOST="$DOTFILE_CN_PYPI_HOST"
  export HF_ENDPOINT="$DOTFILE_CN_HF_ENDPOINT"
}

dotfile_clear_cn_network_settings() {
  if [ "${UV_DEFAULT_INDEX:-}" = "$DOTFILE_CN_PYPI_INDEX" ]; then
    unset UV_DEFAULT_INDEX
  fi
  if [ "${PIP_INDEX_URL:-}" = "$DOTFILE_CN_PYPI_INDEX" ]; then
    unset PIP_INDEX_URL
  fi
  if [ "${PIP_TRUSTED_HOST:-}" = "$DOTFILE_CN_PYPI_HOST" ]; then
    unset PIP_TRUSTED_HOST
  fi
  if [ "${HF_ENDPOINT:-}" = "$DOTFILE_CN_HF_ENDPOINT" ]; then
    unset HF_ENDPOINT
  fi
}

dotfile_apply_region_network_settings() {
  if [ "$(dotfile_read_network_region)" = "CN" ]; then
    dotfile_apply_cn_network_settings
  else
    dotfile_clear_cn_network_settings
  fi
}
# Fetch, reload, and register the generated single-file artifact.
dotfile_download_common_file() {
  mkdir -p "$DOTFILES_DIR"
  curl -sSfL "$DOTFILE_RAW_COMMON_URL" -o "$COMMON_FILE"
}

dotfile_reload_common_file() {
  if [ ! -f "$COMMON_FILE" ]; then
    return 0
  fi

  echo "[dotfile] 重新加载配置..."
  # Reload from the generated single-file artifact so updates take effect in the
  # current shell without requiring a new login shell.
  source "$COMMON_FILE"
  dotfile_refresh_network_region
  dotfile_apply_region_network_settings
  echo "[dotfile] 已重新加载 ✅"
}

dotfile_ensure_bashrc_source() {
  if ! grep -qF "source $COMMON_FILE" "$HOME/.bashrc"; then
    echo "source $COMMON_FILE" >> "$HOME/.bashrc"
    echo "[dotfile] 已自动将 $COMMON_FILE 加入 ~/.bashrc"
  else
    echo "[dotfile] ~/.bashrc 已包含对 $COMMON_FILE 的引用，跳过此步骤。"
  fi
}
# SSH config/key planning and application used by the install flow.
dotfile_install_reset_plan() {
  DOTFILE_INSTALL_PLAN_SSH_CONFIG=()
  DOTFILE_INSTALL_PLAN_SSH_KEYS=()
}

dotfile_plan_sshd_changes() {
  if [ ! -f "$DOTFILE_SSHD_CONFIG_FILE" ]; then
    return
  fi

  local item=""
  for item in "${DOTFILE_SSH_CONFIG_CHECKS[@]}"; do
    local key="${item%% *}"
    local target_value="${item#* }"
    local current_setting
    current_setting=$(grep -E "^[[:space:]]*${key}" "$DOTFILE_SSHD_CONFIG_FILE" 2>/dev/null | head -n 1 || true)

    if [[ -n "$current_setting" ]]; then
      local current_value
      current_value=$(echo "$current_setting" | awk '{print $2}')
      if [[ "$current_value" != "$target_value" ]]; then
        DOTFILE_INSTALL_PLAN_SSH_CONFIG+=("修改配置: ${key} [${current_value}] -> [${target_value}]")
      fi
    else
      local default_value="${DOTFILE_DEFAULT_SSH_VALUES[$key]}"
      if [[ -z "$default_value" ]]; then
        DOTFILE_INSTALL_PLAN_SSH_CONFIG+=("新增配置: ${key} ${target_value} (未知默认值)")
      elif [[ "$default_value" != "$target_value" ]]; then
        DOTFILE_INSTALL_PLAN_SSH_CONFIG+=("新增配置: ${key} ${target_value} (默认为 ${default_value})")
      fi
    fi
  done
}

dotfile_plan_key_changes() {
  local key=""

  if [ ! -f "$DOTFILE_AUTHORIZED_KEYS_FILE" ]; then
    for key in "${DOTFILE_SSH_PUBLIC_KEYS[@]}"; do
      DOTFILE_INSTALL_PLAN_SSH_KEYS+=("新增公钥: ${key:0:50}...")
    done
    return
  fi

  for key in "${DOTFILE_SSH_PUBLIC_KEYS[@]}"; do
    local key_fingerprint
    key_fingerprint=$(echo "$key" | awk '{print $2}')
    if ! grep -qF "$key_fingerprint" "$DOTFILE_AUTHORIZED_KEYS_FILE"; then
      DOTFILE_INSTALL_PLAN_SSH_KEYS+=("新增公钥: ${key:0:50}...")
    fi
  done
}

dotfile_apply_sshd_changes() {
  local use_sudo="$1"
  local config_changed=false
  local sudo_cmd=()
  local item=""

  if [ "$use_sudo" = true ]; then
    sudo_cmd=(sudo)
  fi

  for item in "${DOTFILE_SSH_CONFIG_CHECKS[@]}"; do
    local key="${item%% *}"
    local target_value="${item#* }"
    local current_setting
    current_setting=$(grep -E "^[[:space:]]*${key}" "$DOTFILE_SSHD_CONFIG_FILE" 2>/dev/null | head -n 1 || true)

    if [[ -n "$current_setting" ]]; then
      local current_value
      current_value=$(echo "$current_setting" | awk '{print $2}')
      if [[ "$current_value" != "$target_value" ]]; then
        "${sudo_cmd[@]}" sed -i "s|^[[:space:]]*${key}.*|${key} ${target_value}|g" "$DOTFILE_SSHD_CONFIG_FILE"
        config_changed=true
      fi
    else
      local default_value="${DOTFILE_DEFAULT_SSH_VALUES[$key]}"
      if [[ -z "$default_value" ]] || [[ "$default_value" != "$target_value" ]]; then
        printf '%s\n' "${key} ${target_value}" | "${sudo_cmd[@]}" tee -a "$DOTFILE_SSHD_CONFIG_FILE" > /dev/null
        config_changed=true
      fi
    fi
  done

  if [ "$config_changed" = true ]; then
    echo "[dotfile] 正在重启 SSH 服务..."
    if command -v systemctl >/dev/null 2>&1; then
      "${sudo_cmd[@]}" systemctl restart sshd || "${sudo_cmd[@]}" systemctl restart ssh
    elif command -v service >/dev/null 2>&1; then
      "${sudo_cmd[@]}" service sshd restart || "${sudo_cmd[@]}" service ssh restart
    else
      echo "[dotfile] 警告: 无法自动重启 SSH 服务，请手动重启以应用更改。"
    fi
  fi
}

dotfile_apply_key_changes() {
  local ssh_dir
  ssh_dir=$(dirname "$DOTFILE_AUTHORIZED_KEYS_FILE")

  if [ ! -d "$ssh_dir" ]; then
    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
  fi

  if [ ! -f "$DOTFILE_AUTHORIZED_KEYS_FILE" ]; then
    touch "$DOTFILE_AUTHORIZED_KEYS_FILE"
    chmod 600 "$DOTFILE_AUTHORIZED_KEYS_FILE"
  fi

  local key=""
  for key in "${DOTFILE_SSH_PUBLIC_KEYS[@]}"; do
    local key_fingerprint
    key_fingerprint=$(echo "$key" | awk '{print $2}')
    if ! grep -qF "$key_fingerprint" "$DOTFILE_AUTHORIZED_KEYS_FILE"; then
      printf '%s\n' "$key" >> "$DOTFILE_AUTHORIZED_KEYS_FILE"
    fi
  done
}
# End-user install command, usable from both repo checkouts and curl installs.
dotfile_install() {
  echo "[dotfile] 检查 dotfile 仓库..."

  # Install works in both "full repo checkout" and "curl single-file" modes.
  if [ ! -d "$DOTFILES_DIR/.git" ]; then
    echo "[dotfile] 使用直接下载方式获取 bashrc_common.sh ..."
    if ! dotfile_download_common_file; then
      echo "[dotfile] 错误: 下载 bashrc_common.sh 失败。"
      return 1
    fi
  else
    echo "[dotfile] 更新已有仓库..."
    if ! git -C "$DOTFILES_DIR" pull --quiet; then
      echo "[dotfile] 错误: 更新仓库失败。"
      return 1
    fi
  fi

  dotfile_refresh_network_region
  dotfile_ensure_bashrc_source

  echo "正在扫描系统变更..."
  dotfile_install_reset_plan
  dotfile_plan_sshd_changes
  dotfile_plan_key_changes

  if [ ${#DOTFILE_INSTALL_PLAN_SSH_CONFIG[@]} -eq 0 ] && [ ${#DOTFILE_INSTALL_PLAN_SSH_KEYS[@]} -eq 0 ]; then
    echo "[dotfile] SSH 配置与公钥均已是最新状态，无需操作。"
    echo "[dotfile] 安装完成。重新打开终端或执行 'source $COMMON_FILE' 生效。"
    return 0
  fi

  echo ""
  echo "=========================================="
  echo "         检测到以下待变更项"
  echo "=========================================="

  if [ ${#DOTFILE_INSTALL_PLAN_SSH_CONFIG[@]} -eq 0 ]; then
    echo -e "\n[SSH 配置] 已是最新状态，无需修改。"
  else
    echo -e "\n[SSH 配置变更] (将修改 $DOTFILE_SSHD_CONFIG_FILE):"
    printf "  - %s\n" "${DOTFILE_INSTALL_PLAN_SSH_CONFIG[@]}"
  fi

  if [ ${#DOTFILE_INSTALL_PLAN_SSH_KEYS[@]} -gt 0 ]; then
    echo -e "\n[SSH 公钥变更] (将写入 $DOTFILE_AUTHORIZED_KEYS_FILE):"
    printf "  - %s\n" "${DOTFILE_INSTALL_PLAN_SSH_KEYS[@]}"
  fi

  echo ""
  read -p "[dotfile] 是否执行上述变更？: " -n 1 -r < /dev/tty
  echo ""

  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "[dotfile] 开始执行变更..."

    if [ ${#DOTFILE_INSTALL_PLAN_SSH_CONFIG[@]} -gt 0 ]; then
      if [ -w "$DOTFILE_SSHD_CONFIG_FILE" ]; then
        echo "[dotfile] 检测到有写权限，直接修改配置..."
        dotfile_apply_sshd_changes false
      else
        echo "[dotfile] SSH 配置文件需要管理员权限，正在请求 sudo..."
        if sudo -v 2>/dev/null; then
          dotfile_apply_sshd_changes true
        else
          echo "[dotfile] 错误: 无法获取 sudo 权限，跳过 SSH 配置修改。"
        fi
      fi
    fi

    if [ ${#DOTFILE_INSTALL_PLAN_SSH_KEYS[@]} -gt 0 ]; then
      dotfile_apply_key_changes
    fi

    echo "[dotfile] 变更已完成。"
  else
    echo "[dotfile] 已取消变更。"
  fi

  echo "[dotfile] 安装完成。重新打开终端或执行 'source $COMMON_FILE' 生效。"
}
# CLI subcommands exposed when bashrc_common.sh is executed instead of sourced.
dotfile_cli_usage() {
  cat <<'EOF'
Usage:
  bashrc_common.sh install
  bashrc_common.sh refresh-region
  bashrc_common.sh detect-region
  bashrc_common.sh help
EOF
}

dotfile_cli() {
  local command="${1:-help}"
  shift || true

  case "$command" in
    install)
      dotfile_install "$@"
      ;;
    refresh-region)
      dotfile_refresh_network_region
      ;;
    detect-region)
      dotfile_detect_network_region
      ;;
    help|-h|--help)
      dotfile_cli_usage
      ;;
    *)
      echo "[dotfile] 未知命令: $command" >&2
      dotfile_cli_usage >&2
      return 1
      ;;
  esac
}

dotfile_cli_dispatch_if_executed() {
  local source0="${BASH_SOURCE[0]-}"

  # `source file.sh` keeps BASH_SOURCE[0] as the file path, while `bash -s --`
  # reports `main`. We only dispatch for true execution paths.
  if [ -n "$source0" ] && [ "$source0" != "$0" ] && [ "$source0" != "main" ]; then
    return 0
  fi

  dotfile_cli "$@"
  exit $?
}
# Manual update entrypoint available after the file has been sourced.
# -------- 手动更新命令 --------
update_dotfile() {
  echo "[dotfile] 正在更新..."
  if [ -d "$DOTFILES_DIR/.git" ]; then
    if ! git -C "$DOTFILES_DIR" pull --rebase --autostash; then
      echo "[dotfile] 错误: 更新失败。"
      return 1
    fi
    echo "[dotfile] 更新完成 ✅"
    dotfile_reload_common_file
  else
    echo "[dotfile] 未检测到 git 仓库，使用直接下载方式获取 bashrc_common.sh ..."
    if ! dotfile_download_common_file; then
      echo "[dotfile] 错误: 下载失败。"
      return 1
    fi
    echo "[dotfile] 下载完成 ✅"
    dotfile_reload_common_file
  fi
}
alias update_dotfile='update_dotfile'
alias update-dotfile='update_dotfile'

# Directory movement helpers.
# 目录相关
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
mkcd() { mkdir -p "$1" && cd "$1"; }
alias mcd='mkcd'
alias bd='cd "$OLDPWD"'

# Local port and SSH/network inspection helpers.
# 网络相关
alias ports='netstat -tulnp | grep LISTEN'

ssh_info() {
  if [ -z "$SSH_CONNECTION" ]; then
    echo "Not an SSH session"
    return 1
  fi

  set -- $SSH_CONNECTION
  client_ip=$1
  client_port=$2
  server_ip=$3
  server_port=$4

  echo "Client IP:      $client_ip"
  echo "Client Port:    $client_port"
  echo "Server IP:      $server_ip"
  echo "Server Port:    $server_port"
}
alias ssh-info='ssh_info'

port() {
  # 1. 检查参数
  if [ -z "$1" ]; then
    echo "错误：请输入一个端口号作为参数。"
    echo "用法: $0 <端口号>"
    return 1
  fi

  PORT=$1

  # 2. 使用 lsof -t 精准地只获取 PID
  # -t: Terse output, 只输出 PID，便于脚本处理
  # -sTCP:LISTEN: 只查找状态为 LISTEN 的 TCP 连接，比 grep 更可靠
  PIDS=$(sudo lsof -t -i :${PORT} -sTCP:LISTEN)

  # 3. 检查是否找到了进程
  if [ -z "$PIDS" ]; then
    echo "没有找到在端口 ${PORT} 上监听的进程。"
    return 0
  fi

  echo "在端口 ${PORT} 上找到以下进程的详细信息:"
  echo "====================================================================================================="

  # 4. 使用 ps 命令为每一个找到的 PID 输出详细信息
  #    -p 指定 PID
  #    -o 指定输出格式，这是实现 "htop-like" 的关键
  #
  #    格式说明:
  #    pid      - 进程 ID
  #    user     - 运行该进程的用户名
  #    %cpu     - CPU 使用率
  #    %mem     - 内存使用率
  #    etime    - 进程启动后经过的时间
  #    command  - 完整的命令，包含所有参数 (这是最重要的部分)
  #
  ps ww -p ${PIDS} -o pid,user,%cpu,%mem,etime,command

  echo "====================================================================================================="
}
getip() {
  echo "实际出口IP及网卡信息:"
  ip route get 8.8.8.8 2>/dev/null | 
  awk '{for(i=1;i<=NF;i++){if($i=="dev"){d=$(i+1)}; if($i=="src"){s=$(i+1)}}} END{print d, s}'
  echo "--------------------------------"
  echo "本机所有IP地址:"
  hostname -I
  echo "--------------------------------"
  echo "SSH连接信息（如果适用）:"
  ssh_info || echo "非SSH连接"
}
alias myip='getip'
# Apply region-gated mirrors and define opt-in proxy environment helpers.
dotfile_apply_region_network_settings
# export HF_HUB_ENABLE_HF_TRANSFER=1

proxy() {
  export http_proxy="http://10.77.110.128:20172"
  export https_proxy=$http_proxy
  export no_proxy="localhost,127.0.0.1,::1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
  export HTTP_PROXY=$http_proxy
  export HTTPS_PROXY=$http_proxy
  export NO_PROXY=$no_proxy
}

alias aptp='sudo apt -o Acquire::http::Proxy="$http_proxy" -o Acquire::https::Proxy="$http_proxy"'
# Probe an HTTP proxy from ICMP reachability down to application-layer latency.
function check_proxy() {
    # 1. 解析输入
    local INPUT=${1:-"10.77.110.128:20172"}
    local TARGET_URL="${2:-"https://www.google.com"}"
    if [[ -z "$INPUT" ]]; then
        echo "❌ 用法: check_proxy IP:PORT [TARGET_URL]"
        echo "   示例: check_proxy 10.77.110.128:20172 https://www.google.com"
        return 1
    fi
    
    local IP=${INPUT%:*}
    local PORT=${INPUT#*:}
    # 定义颜色
    local GREEN='\033[0;32m'
    local RED='\033[0;31m'
    local YELLOW='\033[1;33m'
    local NC='\033[0m' # No Color

    echo "------------------------------------------------"
    echo -e "🔍 开始测试代理: ${YELLOW}${INPUT}${NC}"
    echo -e "🎯 目标 URL: ${YELLOW}${TARGET_URL}${NC}"
    echo "------------------------------------------------"

    # --- 阶段 1: IP 连通性测试 (Ping) ---
    echo -n "1. [网络层] Ping IP ($IP)... "
    # 检测系统是 Linux 还是 Mac (Darwin) 来调整 ping 参数
    if [[ "$OSTYPE" == "darwin"* ]]; then
        ping -c 2 -W 1000 "$IP" > /dev/null 2>&1
    else
        ping -c 2 -W 1 "$IP" > /dev/null 2>&1
    fi

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}通 (Pass)${NC}"
    else
        echo -e "${RED}不通 (Fail)${NC} -> 可能被禁 Ping 或 IP 不存在"
        # 注意：Ping 不通不代表代理不能用，继续往下测
    fi

    # --- 阶段 2: 端口开放性测试 (自动回退) ---
    echo -n "2. [传输层] 端口连通性 ($PORT)... "
    local PORT_OPEN=0
    
    # 策略 A: 使用 netcat (nc)
    if command -v nc >/dev/null 2>&1; then
        if nc -z -w 2 "$IP" "$PORT" >/dev/null 2>&1; then
            PORT_OPEN=1
        fi
    # 策略 B: 使用 bash 原生 /dev/tcp (如果 nc 不存在)
    else
        # timeout 命令防止卡死，如果没有 timeout 命令，风险较高但也能跑
        if timeout 2 bash -c "</dev/tcp/$IP/$PORT" >/dev/null 2>&1; then
             PORT_OPEN=1
        fi
    fi

    if [ $PORT_OPEN -eq 1 ]; then
        echo -e "${GREEN}打开 (Open)${NC}"
    else
        echo -e "${RED}关闭或拦截 (Closed/Blocked)${NC}"
        echo "   ⛔ 端口不通，停止后续代理测试。"
        return 1
    fi

    # --- 阶段 3: 代理功能与延迟测试 (自动回退) ---
    echo -n "3. [应用层] 代理握手与延迟... "
    
    # 策略 A: 优先使用 curl (能提供精确的时间分析)
    if command -v curl >/dev/null 2>&1; then
        echo -e "\n   👉 使用 Curl 引擎测试..."
        # 结果捕获
        RESULT=$(curl -o /dev/null -s -w "%{http_code}:%{time_connect}:%{time_total}" --connect-timeout 5 -x "http://$IP:$PORT" "$TARGET_URL")
        
        local HTTP_CODE=$(echo "$RESULT" | cut -d':' -f1)
        local TIME_CONN=$(echo "$RESULT" | cut -d':' -f2)
        local TIME_TOTAL=$(echo "$RESULT" | cut -d':' -f3)

        if [ "$HTTP_CODE" == "200" ] || [ "$HTTP_CODE" == "301" ] || [ "$HTTP_CODE" == "302" ]; then
             echo -e "   状态: ${GREEN}正常 (HTTP $HTTP_CODE)${NC}"
             echo -e "   连接耗时: ${GREEN}${TIME_CONN}s${NC}"
             echo -e "   总延迟:   ${GREEN}${TIME_TOTAL}s${NC}"
        else
             echo -e "   状态: ${RED}失败 (HTTP $HTTP_CODE)${NC} - 代理可能无法连接外网"
        fi

    # 策略 B: 回退使用 wget (如果没有 curl)
    elif command -v wget >/dev/null 2>&1; then
        echo -e "\n   👉 (Curl缺失) 回退使用 Wget + Time 测试..."
        export http_proxy="http://$IP:$PORT"
        export https_proxy="http://$IP:$PORT"
        
        # 使用 time 指令来计算耗时
        # time 的输出格式在不同 shell 下不同，这里直接显示 time 的输出给用户看
        if wget --spider --timeout=5 --tries=1 "$TARGET_URL" >/dev/null 2>&1; then
             echo -e "   状态: ${GREEN}正常 (连接成功)${NC}"
             echo "   (由于没有curl，无法精确分层耗时，请参考下方 time 输出)"
        else
             echo -e "   状态: ${RED}失败${NC}"
        fi
        
        # 清理环境变量
        unset http_proxy https_proxy

    else
        echo -e "${RED}失败${NC}"
        echo "   ❌ 系统既没有 curl 也没有 wget，无法测试 HTTP 代理。"
    fi
    echo "------------------------------------------------"
}
alias check-proxy='check_proxy'
alias proxy-test='check_proxy'
alias proxy_test='check_proxy'

# File backup, search, and archive extraction helpers.
# 文件相关
bak() {
  if [ -z "$1" ]; then
    echo "用法: bak <文件名>"
    return 1
  fi
  cp "$1" "$1.bak_$(date +%Y%m%d_%H%M%S)"
  cp "$1" "$1.bak"
  echo "已创建备份: $1.bak_$(date +%Y%m%d_%H%M%S) 和 $1.bak"
}
f() { find / -iname "*$1*" 2>/dev/null; }
alias untar='tar -xvf'
alias gz='tar -czvf'
alias ungz='tar -xzvf'
extract() {
  if [ -z "$1" ]; then
    echo "用法: extract <压缩文件>"
    return 1
  fi

  if [ ! -f "$1" ]; then
    echo "'$1' 文件不存在"
    return 1
  fi

  case "$1" in
    *.tar) 
      tar -xvf "$1" ;;
    *.tar.gz|*.tgz) 
      tar -xzvf "$1" ;;
    *.tar.bz2|*.tbz|*.tbz2) 
      tar -xjvf "$1" ;;
    *.tar.xz|*.txz) 
      tar -xJvf "$1" ;;
    *.zip) 
      if command -v unzip >/dev/null 2>&1; then
        unzip "$1"
      else
        echo "unzip 未安装"
        return 1
      fi ;;
    *.rar) 
      if command -v unrar >/dev/null 2>&1; then
        unrar x "$1"
      else
        echo "unrar 未安装"
        return 1
      fi ;;
    *.7z) 
      if command -v 7z >/dev/null 2>&1; then
        7z x "$1"
      else
        echo "7z 未安装"
        return 1
      fi ;;
    *.gz) 
      gunzip "$1" ;;
    *.bz2) 
      bunzip2 "$1" ;;
    *.xz) 
      unxz "$1" ;;
    *) 
      echo "'$1' 无法识别的压缩格式" 
      return 1 ;;
  esac
}
# Directory backup and restore helpers based on tar + zstd.
backup_dir () {
    local dir="${1%/}"
    local level="${2:-6}"   # 默认压缩等级 6
    local out="${dir##*/}.tar.zst"  # 自动生成压缩包名

    tar --xattrs --acls --selinux --numeric-owner -cf - "$dir" \
        | zstd -T0 -$level --progress -o "$out"
}

restore_dir () {
    local file="$1"
    tar --xattrs --acls --selinux -I "zstd --progress" -xf "$file"
}
alias backup-dir='backup_dir'
alias restore-dir='restore_dir'

# Quick GPU monitoring aliases.
# GPU 监控
alias wnv='watch -n 1 nvidia-smi'
alias wnvidia='watch -n 1 nvidia-smi'
alias nvidia-htop='nvidia-htop.py -l -c -m'
alias wnvidia-htop='watch -n 1 nvidia-htop.py -l -c -m'

# Python virtual environment activation shortcuts.
a() {
    local base="."
    if [ $# -gt 0 ]; then
        base="$1"
    fi

    # 去掉末尾的斜杠
    base="${base%/}"

    local cand1="$base/.venv/bin/activate"
    local cand2="$base/bin/activate"

    if [ -f "$cand1" ]; then
        source "$cand1"
        return
    fi

    if [ -f "$cand2" ]; then
        source "$cand2"
        return
    fi

    echo "❌ 未找到虚拟环境：$cand1 或 $cand2"
    return 1
}
alias va=a

alias da=deactivate
# Simple Hugging Face download wrappers.
hf_mirror_download() {
  HF_ENDPOINT=https://hf-mirror.com python3 -c "from huggingface_hub import snapshot_download; snapshot_download('$1')"
}
alias hf-mirror-download='hf_mirror_download'
hf_download() {
 python3 -c "from huggingface_hub import snapshot_download; snapshot_download('$1')"
}
alias hf-download='hf_download'
# vLLM throughput benchmark wrapper.
vllm_bench() {
  model=${1:-"Qwen/Qwen3-4B-Instruct-2507"}
  input_len=${2:-4096}
  output_len=${3:-256}
  num_prompts=${4:-100}

  # default max_model_len = input_len + output_len
  if [ -n "$5" ]; then
    max_model_len=$5
  else
    max_model_len=$((input_len + output_len))
  fi

  vllm bench throughput \
    --gpu-memory-utilization 0.9 \
    --model "$model" \
    --dataset-name random \
    --num-prompts "$num_prompts" \
    --input-len "$input_len" \
    --output-len "$output_len" \
    --max-model-len "$max_model_len" \
    --async-engine
}

alias hf_bench='vllm_bench'
alias vllm-bench='vllm_bench'

# Claude CLI aliases and profile switching.
alias claude='CLAUDE_CODE_MAX_OUTPUT_TOKENS=64000 IS_SANDBOX=1 claude --dangerously-skip-permissions'
alias codex='codex --dangerously-bypass-approvals-and-sandbox'
claude_switch() {
    # if exist ~/.claude/settings.json.$1, copy to ~/.claude/settings.json
    if [ -f ~/.claude/settings.json.$1 ]; then
        cp ~/.claude/settings.json.$1 ~/.claude/settings.json
        echo "Switched to Claude profile: $1"
    else
        echo "Profile $1 does not exist."
        ls -1 ~/.claude/settings.json.*
    fi
    cat ~/.claude/settings.json
}
alias cls='claude_switch'
alias claude-switch='claude_switch'
# Codex CLI aliases and profile switching.
codex_switch() {
    # if exist ~/.codex/auth.json.$1, copy auth.json.
    # if exist ~/.codex/config.toml.$1, merge protected fields into ~/.codex/config.toml as well.
    local profile="${1}"
    local src_config="${HOME}/.codex/config.toml.${profile}"
    local src_auth="${HOME}/.codex/auth.json.${profile}"
    local dst_config="${HOME}/.codex/config.toml"
    local dst_auth="${HOME}/.codex/auth.json"
    local openai_auth_backup="${HOME}/.codex/auth.json.openai"

    local has_src_config="0"
    if [ -f "$src_config" ]; then
        has_src_config="1"
    fi

    if [ -f "$src_auth" ]; then
        # Preserve the current ChatGPT login before profile switch overwrites auth.json.
        if [ -f "$dst_auth" ] && grep -Eq '"auth_mode"[[:space:]]*:[[:space:]]*"chatgpt"' "$dst_auth"; then
            cp "$dst_auth" "$openai_auth_backup"
        fi

        cp "$src_auth" "$dst_auth"

        if [ "$has_src_config" = "1" ]; then
            if [ -f "$dst_config" ]; then
                local backup_root="${HOME}/.codex/backups"
                local backup_day_dir="${backup_root}/$(date +%F)"
                local backup_file="${backup_day_dir}/config.toml.$(date +%F_%H%M%S)"
                local merged_file
                local tmp_projects
                local tmp_model
                local tmp_model_reasoning
                merged_file="$(mktemp "${dst_config}.merged.XXXXXX")"
                tmp_projects="$(mktemp "${dst_config}.projects.XXXXXX")"
                tmp_model="$(mktemp "${dst_config}.model.XXXXXX")"
                tmp_model_reasoning="$(mktemp "${dst_config}.reasoning.XXXXXX")"

                mkdir -p "$backup_day_dir"
                cp "$dst_config" "$backup_file"

                awk '
                    /^\[projects(\..*)?\][[:space:]]*$/ { in_projects=1; print; next }
                    in_projects && /^\[[^]]+\][[:space:]]*$/ { in_projects=0 }
                    in_projects { print }
                ' "$dst_config" > "$tmp_projects"

                awk 'BEGIN { found=0 }
                    /^[[:space:]]*model[[:space:]]*=/ && found==0 {
                        print
                        found=1
                        exit
                    }
                ' "$dst_config" > "$tmp_model"

                awk 'BEGIN { found=0 }
                    /^[[:space:]]*model_reasoning_effort[[:space:]]*=/ && found==0 {
                        print
                        found=1
                        exit
                    }
                ' "$dst_config" > "$tmp_model_reasoning"
            python3 - "$src_config" "$merged_file" "$tmp_projects" "$tmp_model" "$tmp_model_reasoning" <<'PY'
import sys
from pathlib import Path

src_config_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])
projects_path = Path(sys.argv[3])
model_path = Path(sys.argv[4])
reasoning_path = Path(sys.argv[5])

source_text = src_config_path.read_text()

projects_block = projects_path.read_text().rstrip("\n")
model_line = model_path.read_text().rstrip("\n")
reasoning_line = reasoning_path.read_text().rstrip("\n")

if projects_block:
    import re
    source_text = re.sub(
        r'(?ms)^\[projects(?:\.[^]]+)?\][ \t]*\n.*?(?=^\[[^]]+\]|\Z)',
        '',
        source_text
    )
    source_text = f"{source_text.rstrip(chr(10))}\n\n{projects_block}\n"

if model_line:
    import re
    source_text, count = re.subn(r'(?m)^\s*model\s*=.*$', model_line, source_text, count=1)
    if count == 0:
        if not source_text.endswith('\n'):
            source_text += '\n'
        source_text += f"{model_line}\n"

if reasoning_line:
    import re
    source_text, count = re.subn(
        r'(?m)^\s*model_reasoning_effort\s*=.*$',
        reasoning_line,
        source_text,
        count=1
    )
    if count == 0:
        if not source_text.endswith('\n'):
            source_text += '\n'
        source_text += f"{reasoning_line}\n"

out_path.write_text(source_text)
PY

                mv "$merged_file" "$dst_config"
                rm -f "$tmp_projects" "$tmp_model" "$tmp_model_reasoning"
            fi
            if [ -f "$dst_config" ]; then
                echo "Switched to Codex profile: $1"
            else
                cp "$src_config" "$dst_config"
                echo "No local ~/.codex/config.toml was found, copied from profile: $1"
            fi
        else
            echo "⚠️  No config.toml for profile $1, only auth.json has been switched."
            if [ -f "$dst_config" ]; then
                echo "Kept current ~/.codex/config.toml"
            else
                echo "No ~/.codex/config.toml exists locally yet."
            fi
        fi
    else
        echo "Profile $1 does not exist."
        ls -1 ~/.codex/config.toml.*
        ls -1 ~/.codex/auth.json.*
    fi

    if [ -f "$dst_config" ]; then
        cat "$dst_config"
    else
        echo "~/.codex/config.toml does not exist."
    fi
}
alias cxs='codex_switch'
alias codex-switch='codex_switch'

# Systemd shortcuts plus completion remapping for the custom aliases.
# systemctl 相关
alias sup='systemctl start'
alias sdown='systemctl stop'
alias sstatus='systemctl status'
alias ssta='systemctl status'

# alias su='systemctl --user'
alias suup='systemctl --user start'
alias sudown='systemctl --user stop'
alias sustatus='systemctl --user status'
alias susta='systemctl --user status'

_systemctl_alias_completion() {
    # COMP_WORDS 是包含当前命令行所有单词的数组
    # COMP_CWORD 是光标所在单词的索引
    local alias_cmd="${COMP_WORDS[0]}"
    local words_after_alias=("${COMP_WORDS[@]:1}")
    
    # 使用 case 语句根据不同的别名，构建出实际的命令
    case "$alias_cmd" in
        sup)
            COMP_WORDS=(systemctl start "${words_after_alias[@]}")
            COMP_CWORD=$((COMP_CWORD + 1))
            ;;
        sdown)
            COMP_WORDS=(systemctl stop "${words_after_alias[@]}")
            COMP_CWORD=$((COMP_CWORD + 1))
            ;;
        sstatus|ssta) # 使用 | 将多个别名映射到同一个命令
            COMP_WORDS=(systemctl status "${words_after_alias[@]}")
            COMP_CWORD=$((COMP_CWORD + 1))
            ;;
        su)
            COMP_WORDS=(systemctl --user "${words_after_alias[@]}")
            COMP_CWORD=$((COMP_CWORD + 1))
            ;;
        suup)
            COMP_WORDS=(systemctl --user start "${words_after_alias[@]}")
            # 这里增加了2个单词 (--user, start)，所以索引要加2
            COMP_CWORD=$((COMP_CWORD + 2))
            ;;
        sudown)
            COMP_WORDS=(systemctl --user stop "${words_after_alias[@]}")
            COMP_CWORD=$((COMP_CWORD + 2))
            ;;
        sustatus|susta)
            COMP_WORDS=(systemctl --user status "${words_after_alias[@]}")
            COMP_CWORD=$((COMP_CWORD + 2))
            ;;
    esac

    # 调用 systemctl 原本的补全函数来处理我们伪造的命令行
    _systemctl
}
complete -F _systemctl_alias_completion \
    sup sdown sstatus ssta \
    su suup sudown sustatus susta
# PATH inspection shortcut.
alias path='echo -e ${PATH//:/\\n}'
# Pre-tuned aria2 download presets.
alias aria2c-fast='aria2c --max-connection-per-server=16 --split=16 --min-split-size=1M --continue=true'
alias aria2c-large='aria2c --max-connection-per-server=16 --split=16 --min-split-size=20M --continue=true'
# Aggregate process stats for commands matching a keyword.
pstat() {
    if [ -z "$1" ]; then
        echo "Usage: pstat <keyword>"
        return 1
    fi

    keyword="$1"

    echo "Processes matching: $keyword"
    echo "-----------------------------------------------------------------------"
    printf "%-8s %-8s %-8s %-10s %s\n" "PID" "CPU%" "MEM%" "RSS(MB)" "CMD"

    ps ax -o pid,pcpu,pmem,rss,cmd | grep -F "$keyword" | grep -v grep | while read pid cpu mem rss cmd; do
        rss_mb=$(awk -v r="$rss" 'BEGIN{printf "%.1f", r/1024}')
        printf "%-8s %-8s %-8s %-10s %s\n" "$pid" "$cpu" "$mem" "$rss_mb" "$cmd"
    done

    cpu_sum=$(ps ax -o pcpu,cmd | grep -F "$keyword" | grep -v grep | awk '{sum+=$1} END{print sum}')
    mem_sum=$(ps ax -o pmem,cmd | grep -F "$keyword" | grep -v grep | awk '{sum+=$1} END{print sum}')
    rss_sum=$(ps ax -o rss,cmd | grep -F "$keyword" | grep -v grep | awk '{sum+=$1} END{printf "%.1f", sum/1024}')

    echo "-----------------------------------------------------------------------"
    echo "Total CPU%: $cpu_sum"
    echo "Total MEM%: $mem_sum"
    echo "Total RSS : $rss_sum MB"
}

# Run an interactive shell or one-off command inside a container.
# docker 相关
dockerbash() {
  # 检查是否提供了至少一个参数（容器名）
  if [ -z "$1" ]; then
    echo "用法: dockerbash <容器ID或名称> [要在容器中执行的命令...]"
    return 1
  fi

  # 将第一个参数（容器名）保存到一个变量中，以便后续使用
  local container_id="$1"

  # 检查参数总数是否大于1。
  # 如果参数总数大于1，意味着除了容器名，还提供了要执行的命令。
  if [ "$#" -gt 1 ]; then
    # “shift”命令会移除第一个参数（$1），
    # 剩下的所有参数（$@）就正好是我们要执行的命令。
    shift
    docker exec "$container_id" /bin/bash -c "$@"
  else
    # 如果参数总数只有1，就执行默认行为：启动一个交互式的bash shell。
    docker exec -it "$container_id" /bin/bash
  fi
}
# Short aliases for containerized local model runtimes.
alias ollamad='docker exec -it ollama ollama'
alias vllamad='docker exec -it vllama vllama'
# Stream Docker images over SSH without writing intermediate tarballs to disk.
# ========== Docker 镜像传输函数 ==========
# 使用方法: docker_push <ssh_target> [ssh_opts...] <image_name> [--force]
#           docker_pull <ssh_target> [ssh_opts...] <image_name> [--force]
# 示例: docker_push user@host hello-world:latest
#       docker_push user@host -p 2222 nginx:alpine --force

_docker_image_sync() {
    local func_name="${FUNCNAME[1]}"
    local force=false
    local args=()

    # 解析参数，提取 --force
    for arg in "$@"; do
        if [[ "$arg" == "--force" ]]; then
            force=true
        else
            args+=("$arg")
        fi
    done

    if [ ${#args[@]} -lt 2 ]; then
        echo "Usage: $func_name <ssh_target> [ssh_opts...] <image_name> [--force]"
        echo "Example: $func_name user@host hello-world:latest"
        echo "         $func_name user@host -p 2222 nginx:alpine --force"
        return 1
    fi

    local image="${args[-1]}"
    local remote_args=("${args[@]:0:${#args[@]}-1}")
    local ssh_target="${remote_args[0]}"

    # 构建 SSH 命令
    local ssh_cmd="ssh"
    local ssh_opts=""
    if [ ${#remote_args[@]} -gt 1 ]; then
        ssh_opts="${remote_args[@]:1}"
        ssh_cmd="ssh $ssh_opts"
    fi

    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🐳 Docker Image Sync: $image"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # 1. 检查本地 docker
    if ! command -v docker &>/dev/null; then
        echo "❌ 错误: 本地未安装 docker"
        return 1
    fi

    # 2. 检查本地 zstd
    if ! command -v zstd &>/dev/null; then
        echo "❌ 错误: 本地未安装 zstd"
        return 1
    fi

    # 3. 检查远程 docker
    echo "📡 检查远程环境..."
    if ! $ssh_cmd "$ssh_target" 'command -v docker' &>/dev/null; then
        echo "❌ 错误: 远程主机 $ssh_target 未安装 docker"
        return 1
    fi

    # 4. 检查远程 zstd
    if ! $ssh_cmd "$ssh_target" 'command -v zstd' &>/dev/null; then
        echo "❌ 错误: 远程主机 $ssh_target 未安装 zstd"
        return 1
    fi
    echo "✅ 远程环境检查通过"

    if [[ "$func_name" == "docker_push" ]]; then
        _docker_image_sync_impl "push" "$ssh_target" "$ssh_opts" "$image" "$force"
    elif [[ "$func_name" == "docker_pull" ]]; then
        _docker_image_sync_impl "pull" "$ssh_target" "$ssh_opts" "$image" "$force"
    else
        echo "❌ 未知函数: $func_name"
        return 1
    fi
}

_docker_image_sync_impl() {
    local sync_direction="$1"
    local ssh_target="$2"
    local ssh_opts="$3"
    local image="$4"
    local force="$5"
    local ssh_cmd="ssh"
    [[ -n "$ssh_opts" ]] && ssh_cmd="ssh $ssh_opts"

    if [[ "$sync_direction" == "push" ]]; then
        echo ""
        echo "📤 推送镜像: $image"
        echo "   本地 → $ssh_target"
        echo ""

        # 检查本地镜像是否存在
        if ! docker image inspect "$image" &>/dev/null; then
            echo "❌ 错误: 本地不存在镜像 '$image'"
            echo "   可用镜像:"
            docker images --format "   - {{.Repository}}:{{.Tag}}" | head -10
            return 1
        fi

        # 检查远程镜像是否存在
        if $ssh_cmd "$ssh_target" "docker image inspect '$image'" &>/dev/null; then
            if [[ "$force" != "true" ]]; then
                echo "⚠️  警告: 远程已存在镜像 '$image'"
                echo "   使用 --force 参数覆盖，或先在远程删除镜像"
                return 1
            else
                echo "⚠️  远程已存在镜像，将覆盖 (--force)"
            fi
        fi

        local image_size
        image_size=$(docker image inspect "$image" --format '{{.Size}}' 2>/dev/null)
    elif [[ "$sync_direction" == "pull" ]]; then
        echo ""
        echo "📥 拉取镜像: $image"
        echo "   $ssh_target → 本地"
        echo ""

        # 检查远程镜像是否存在
        if ! $ssh_cmd "$ssh_target" "docker image inspect '$image'" &>/dev/null; then
            echo "❌ 错误: 远程不存在镜像 '$image'"
            echo "   远程可用镜像:"
            $ssh_cmd "$ssh_target" "docker images --format '   - {{.Repository}}:{{.Tag}}'" | head -10
            return 1
        fi

        # 检查本地镜像是否存在
        if docker image inspect "$image" &>/dev/null; then
            if [[ "$force" != "true" ]]; then
                echo "⚠️  警告: 本地已存在镜像 '$image'"
                echo "   使用 --force 参数覆盖，或先删除本地镜像"
                return 1
            else
                echo "⚠️  本地已存在镜像，将覆盖 (--force)"
            fi
        fi

        local image_size
        image_size=$($ssh_cmd "$ssh_target" "docker image inspect '$image' --format '{{.Size}}'" 2>/dev/null)
    else
        echo "❌ 未知方向: $sync_direction"
        return 1
    fi

    local image_size_human
    image_size_human=$(numfmt --to=iec-i --suffix=B "$image_size" 2>/dev/null || echo "unknown")
    echo "📦 镜像大小: $image_size_human"
    echo ""

    # 传输: docker save | zstd | pv | ssh | zstd -d | docker load
    echo "🚀 开始传输..."
    local start_time
    start_time=$(date +%s)

    _docker_image_transfer_data "$sync_direction" "$ssh_target" "$ssh_opts" "$image"
    local ret=$?
    local end_time
    end_time=$(date +%s)
    local duration=$((end_time - start_time))

    echo ""
    if [ $ret -eq 0 ]; then
        if [[ "$sync_direction" == "push" ]]; then
            echo "✅ 推送完成! 耗时: ${duration}s"
            if $ssh_cmd "$ssh_target" "docker image inspect '$image'" &>/dev/null; then
                echo "✅ 远程镜像验证成功"
            fi
        else
            echo "✅ 拉取完成! 耗时: ${duration}s"
            if docker image inspect "$image" &>/dev/null; then
                echo "✅ 本地镜像验证成功"
            fi
        fi
    else
        if [[ "$sync_direction" == "push" ]]; then
            echo "❌ 推送失败"
        else
            echo "❌ 拉取失败"
        fi
        return 1
    fi
}

_docker_image_transfer_data() {
    local sync_direction="$1"
    local ssh_target="$2"
    local ssh_opts="$3"
    local image="$4"

    local ssh_cmd="ssh"
    [[ -n "$ssh_opts" ]] && ssh_cmd="ssh $ssh_opts"

    if command -v pv &>/dev/null; then
        if [[ "$sync_direction" == "push" ]]; then
            docker save "$image" | zstd -T0 -3 | pv -N "传输中" -f | \
                $ssh_cmd "$ssh_target" 'zstd -d -T0 | docker load'
        else
            $ssh_cmd "$ssh_target" "docker save '$image' | zstd -T0 -3" | \
                pv -N "传输中" -f | zstd -d -T0 | docker load
        fi
    elif command -v dd &>/dev/null && dd --help 2>&1 | grep -q "status"; then
        echo "   (提示: 安装 pv 可显示更完整的进度条/ETA)"
        if [[ "$sync_direction" == "push" ]]; then
            docker save "$image" | zstd -T0 -3 | dd status=progress | \
                $ssh_cmd "$ssh_target" 'zstd -d -T0 | docker load'
        else
            $ssh_cmd "$ssh_target" "docker save '$image' | zstd -T0 -3" | \
                dd status=progress | zstd -d -T0 | docker load
        fi
    else
        echo "   (提示: 安装 pv 可显示进度条)"
        if [[ "$sync_direction" == "push" ]]; then
            docker save "$image" | zstd -T0 -3 --progress | \
                $ssh_cmd "$ssh_target" 'zstd -d -T0 | docker load'
        else
            $ssh_cmd "$ssh_target" "docker save '$image' | zstd -T0 -3 --progress" | \
                zstd -d -T0 | docker load
        fi
    fi
}

# 对外接口
docker_push() { _docker_image_sync "$@"; }
docker_pull() { _docker_image_sync "$@"; }
alias docker-push='docker_push'
alias docker-pull='docker_pull'

# Shared rsync/scp sync engine used by all higher-level sync commands.
_remote_sync_scp_fallback() {
    local mode="$1"
    local local_dir="$2"
    local remote_dir="$3"
    local remote_target="$4"
    local patterns_csv="$5"
    local extra_opts="$6"
    shift 6
    local remote_opts=("$@")

    local local_dir_clean="${local_dir%/}"
    local remote_dir_clean="${remote_dir%/}"
    local ignore_existing=0
    if [[ " $extra_opts " == *" --ignore-existing "* ]]; then
        ignore_existing=1
    fi

    local -a scp_cmd=(scp -r)
    if [ ${#remote_opts[@]} -gt 0 ]; then
        scp_cmd+=("${remote_opts[@]}")
    fi

    local -a ssh_cmd=(ssh)
    if [ ${#remote_opts[@]} -gt 0 ]; then
        ssh_cmd+=("${remote_opts[@]}")
    fi

    case "$mode" in
        push)
            "${ssh_cmd[@]}" "$remote_target" "mkdir -p $remote_dir_clean"
            if [ $? -ne 0 ]; then
                return 1
            fi
            if [ -z "$patterns_csv" ]; then
                "${scp_cmd[@]}" "$local_dir_clean/." "${remote_target}:${remote_dir_clean}/"
                return $?
            fi

            local IFS='|'
            local -a patterns=()
            local pattern
            local normalized_pattern
            local local_file
            local has_source=0
            read -r -a patterns <<< "$patterns_csv"
            IFS=$' \t\n'

            for pattern in "${patterns[@]}"; do
                normalized_pattern="${pattern%/}"
                local matched=0
                local -a matched_files=()
                while IFS= read -r -d '' local_file; do
                    matched_files+=("$local_file")
                done < <(find "$local_dir_clean" -mindepth 1 -maxdepth 1 \
                    \( -type f -o -type d \) -name "$normalized_pattern" -print0)

                if [ ${#matched_files[@]} -eq 0 ]; then
                    echo "⚠️  跳过不存在的路径: $local_dir_clean/$normalized_pattern"
                    continue
                fi

                for local_file in "${matched_files[@]}"; do
                    has_source=1
                    # `--ignore-existing` is implemented here so the scp fallback
                    # preserves rsync's "seed missing files only" behavior.
                    if [ "$ignore_existing" -eq 1 ] && \
                        "${ssh_cmd[@]}" "$remote_target" "[ -e ${remote_dir_clean}/$(basename "$local_file") ]"; then
                        echo "ℹ️  目标已存在，跳过: ${remote_dir_clean}/$(basename "$local_file")"
                        matched=1
                        continue
                    fi
                    "${scp_cmd[@]}" "$local_file" "${remote_target}:${remote_dir_clean}/"
                    if [ $? -ne 0 ]; then
                        return 1
                    fi
                    matched=1
                done
                if [ "$matched" -eq 0 ]; then
                    echo "⚠️  未匹配到路径: $local_dir_clean/$normalized_pattern"
                fi
            done
            if [ "$has_source" -eq 0 ]; then
                echo "⚠️  未发现可同步路径，已按无变更处理"
            fi
            ;;
        pull)
            mkdir -p "$local_dir_clean"
            if [ -z "$patterns_csv" ]; then
                "${scp_cmd[@]}" "${remote_target}:${remote_dir_clean}/." "$local_dir_clean/"
                return $?
            fi

            local IFS='|'
            local -a patterns=()
            local pattern
            local normalized_pattern
            local remote_files
            local found_any=0
            read -r -a patterns <<< "$patterns_csv"
            IFS=$' \t\n'

            for pattern in "${patterns[@]}"; do
                normalized_pattern="${pattern%/}"
                remote_files=$("${ssh_cmd[@]}" "$remote_target" \
                    "for f in ${remote_dir_clean}/${normalized_pattern}; do
                        [ -e \"$f\" ] && printf '%s\n' \"$f\";
                    done")
                if [ -z "$remote_files" ]; then
                    echo "⚠️  未找到远程路径: ${remote_dir_clean}/${normalized_pattern}"
                    continue
                fi

                while IFS= read -r remote_file; do
                    [ -z "$remote_file" ] && continue
                    found_any=1
                    if [ "$ignore_existing" -eq 1 ] && [ -e "$local_dir_clean/$(basename "$remote_file")" ]; then
                        echo "ℹ️  本地已存在，跳过: $local_dir_clean/$(basename "$remote_file")"
                        continue
                    fi
                    "${scp_cmd[@]}" "${remote_target}:${remote_file}" "$local_dir_clean/"
                    if [ $? -ne 0 ]; then
                        return 1
                    fi
                done <<< "$remote_files"
            done
            if [ "$found_any" -eq 0 ]; then
                echo "⚠️  未找到可同步路径，已按无变更处理"
            fi
            ;;
        *)
            echo "Unknown sync mode: $mode"
            return 1
            ;;
    esac
    return 0
}

_remote_sync() {
    local mode="$1"
    local local_dir="$2"
    local remote_dir="$3"
    local patterns_csv="$4"
    local sync_label="$5"
    local extra_opts="$6"
    shift 6

    if [ "$mode" != "push" ] && [ "$mode" != "pull" ]; then
        echo "Unknown sync mode: $mode"
        return 1
    fi

    if [ $# -lt 1 ]; then
        echo "Usage: ${sync_label}_${mode} <ssh_target> [ssh_opts...]"
        echo "Example: ${sync_label}_${mode} user@host -p 2022"
        return 1
    fi

    local -a remote_args=("$@")
    local remote_target="${remote_args[0]}"

    local -a remote_opts=()
    if [ ${#remote_args[@]} -gt 1 ]; then
        remote_opts=("${remote_args[@]:1}")
    fi

    local ssh_cmd="ssh"
    if [ ${#remote_opts[@]} -gt 0 ]; then
        ssh_cmd+=" ${remote_opts[*]}"
    fi

    local -a rsync_opts=(--mkpath)
    if [ -n "$extra_opts" ]; then
        # extra_opts is passed as shell-style flags such as `--links` or
        # `--ignore-existing`; split it so rsync receives each flag separately.
        # shellcheck disable=SC2206
        local -a parsed_extra_opts=($extra_opts)
        rsync_opts+=("${parsed_extra_opts[@]}")
    fi

    if [ "$mode" = "push" ]; then
        echo "Pushing local -> remote"
        echo "From: $local_dir"
        echo "To:   ${remote_target}:$remote_dir"
    else
        echo "Pulling remote -> local"
        echo "From: ${remote_target}:$remote_dir"
        echo "To:   $local_dir"
    fi

    local rsync_exit=1
    if [ -z "$patterns_csv" ]; then
        rsync -avzP "${rsync_opts[@]}" -e "$ssh_cmd" \
            "$local_dir" "${remote_target}:$remote_dir"
        rsync_exit=$?
    else
        local -a patterns=()
        local IFS='|'
        read -r -a patterns <<< "$patterns_csv"
        IFS=$' \t\n'

        local -a rsync_includes=()
        local pattern
        for pattern in "${patterns[@]}"; do
            rsync_includes+=(--include="$pattern")
            # A trailing slash marks a top-level directory pattern. rsync needs
            # the directory itself and all descendants included before exclude='*'.
            if [[ "$pattern" == */ ]]; then
                rsync_includes+=(--include="${pattern}***")
            fi
        done

        if [ "$mode" = "push" ]; then
            rsync -avzP "${rsync_opts[@]}" -e "$ssh_cmd" \
                "${rsync_includes[@]}" \
                --exclude='*' \
                "$local_dir" "${remote_target}:$remote_dir"
            rsync_exit=$?
        else
            rsync -avzP "${rsync_opts[@]}" -e "$ssh_cmd" \
                "${rsync_includes[@]}" \
                --exclude='*' \
                "${remote_target}:$remote_dir" "$local_dir"
            rsync_exit=$?
        fi
    fi

    if [ $rsync_exit -eq 0 ]; then
        echo "Sync complete"
        return 0
    fi

    echo "⚠️  rsync 同步失败，自动回退到 scp ..."
    _remote_sync_scp_fallback "$mode" "$local_dir" "$remote_dir" "$remote_target" "$patterns_csv" "$extra_opts" "${remote_opts[@]}"
    if [ $? -eq 0 ]; then
        echo "✅ scp 回退同步完成"
        return 0
    fi
    echo "❌ scp 回退同步失败"
    return 1
}
# Sync Hugging Face model cache directories between machines.
_hf_sync() {
    if [ $# -lt 2 ]; then
        local func_name="${FUNCNAME[1]}"
        echo "Usage: $func_name <ssh_target> [ssh_opts...] <model_name>"
        echo "Example: $func_name user@host -p 2022 Qwen/Qwen3-8B"
        return 1
    fi

    local model="${@: -1}"
    local remote_args=("${@:1:$#-1}")
    local mode
    case "${FUNCNAME[1]}" in
        hf_push) mode="push" ;;
        hf_pull) mode="pull" ;;
        *) echo "❌ Unknown function name"; return 1 ;;
    esac

    local local_base="$HOME/.cache/huggingface/hub"
    local model_dir="models--${model//\//--}"
    local local_dir="$local_base/$model_dir/"
    local remote_dir="~/.cache/huggingface/hub/$model_dir/"

    echo "🔄 Syncing HuggingFace model cache: $model"
    _remote_sync "$mode" "$local_dir" "$remote_dir" "" "hf" "--links" "${remote_args[@]}"
}

hf_push() { _hf_sync "$@"; }
hf_pull() { _hf_sync "$@"; }
alias hf-push='hf_push'
alias hf-pull='hf_pull'
# Sync arbitrary home-directory subtrees between machines.
_data_sync() {
    if [ $# -lt 2 ]; then
        local func_name="${FUNCNAME[1]}"
        echo "Usage: $func_name <ssh_target> [ssh_opts...] <dir_name>"
        echo "Example: $func_name user@host -p 2022 data"
        return 1
    fi

    local dir="${@: -1}"
    local remote_args=("${@:1:$#-1}")
    local mode
    case "${FUNCNAME[1]}" in
        data_push) mode="push" ;;
        data_pull) mode="pull" ;;
        *) echo "❌ Unknown function name"; return 1 ;;
    esac

    local local_dir="$HOME/$dir"
    local remote_dir="~/$dir"

    echo "🔄 Syncing directory: $dir"
    _remote_sync "$mode" "$local_dir/" "$remote_dir/" "" "data" "--links" "${remote_args[@]}"
}

# 对外接口
data_push() { _data_sync "$@"; }
data_pull() { _data_sync "$@"; }
alias data-push='data_push'
alias data-pull='data_pull'
# List cached Hugging Face models grouped by namespace prefix.
hf_list() {
    local CACHE_DIR="${HF_HOME:-$HOME/.cache}/huggingface/hub"

    if [ ! -d "$CACHE_DIR" ]; then
        echo "Cache directory does not exist: $CACHE_DIR"
        return 1
    fi

    declare -A grouped_models

    # 遍历所有模型目录
    for dir in "$CACHE_DIR"/models--*/; do
        local model_dir
        model_dir=$(basename "$dir")
        # 去掉 models-- 前缀
        local model_name="${model_dir//models--/}"
        # 将 -- 替换为 /，得到 user/model-name
        model_name="${model_name//--//}"
        # 取前缀作为分组 key
        local prefix="${model_name%%/*}"
        grouped_models["$prefix"]+="$model_name"$'\n'
    done

    echo "Models in Hugging Face cache (grouped by prefix):"
    echo "-------------------------------------------------"

    # 输出分组，前缀排序
    for prefix in $(printf "%s\n" "${!grouped_models[@]}" | sort); do
        echo "$prefix:"
        while IFS= read -r model; do
            [ -z "$model" ] && continue
            echo "  - $model"
        done <<< "$(printf "%s" "${grouped_models[$prefix]}" | sort)"
    done
}
alias hf-list='hf_list'
# Sync Claude local config files between machines.
_claude_sync() {
    local sync_mode="$1"
    shift
    # Claude settings can be machine-specific, so push/pull only seeds missing
    # files on the receiver and never overwrites an existing one.
    _remote_sync "$sync_mode" "$HOME/.claude/" "~/.claude/" "settings.json|settings.json.*" "claude" "--ignore-existing" "$@"
}

claude_push() { _claude_sync "push" "$@"; }
claude_pull() { _claude_sync "pull" "$@"; }
alias claude-push='claude_push'
alias claude-pull='claude_pull'
# Sync Codex auth/config files between machines.
_codex_sync() {
    local sync_mode="$1"
    shift
    # Codex auth/config files can be machine-specific, so push/pull only seeds
    # missing files on the receiver and never overwrites an existing one.
    _remote_sync "$sync_mode" "$HOME/.codex/" "~/.codex/" "auth.json|auth.json.*|config.toml|config.toml.*" "codex" "--ignore-existing" "$@"
}

codex_push() { _codex_sync "push" "$@"; }
codex_pull() { _codex_sync "pull" "$@"; }
alias codex-push='codex_push'
alias codex-pull='codex_pull'
# Merge only the user-selected provider into the destination JSON so machine-
# specific OpenCode settings stay local while the active provider follows sync.
_opencode_merge_provider_json() {
    local source_json="$1"
    local dest_json="$2"
    local output_json="$3"

    python3 - "$source_json" "$dest_json" "$output_json" <<'PY'
import json
import os
import sys

source_path, dest_path, output_path = sys.argv[1:4]


def load_json(path, allow_missing):
    if allow_missing and (not os.path.exists(path) or os.path.getsize(path) == 0):
        return {}

    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)

    if not isinstance(data, dict):
        print(f"JSON root must be an object: {path}", file=sys.stderr)
        raise SystemExit(1)

    return data


source_data = load_json(source_path, allow_missing=False)
if "provider" not in source_data:
    print(f"provider field not found in {source_path}", file=sys.stderr)
    raise SystemExit(3)

dest_data = load_json(dest_path, allow_missing=True)
dest_data["provider"] = source_data["provider"]

with open(output_path, "w", encoding="utf-8") as handle:
    json.dump(dest_data, handle, indent=2, ensure_ascii=False)
    handle.write("\n")
PY
}

# OpenCode's main config mixes one portable provider choice with machine-local
# settings, so opencode sync handles opencode.json separately from file-level rsync.
_opencode_sync_provider() {
    local sync_mode="$1"
    shift

    if [ $# -lt 1 ]; then
        echo "Usage: opencode_${sync_mode} <ssh_target> [ssh_opts...]"
        echo "Example: opencode_${sync_mode} user@host -p 2022"
        return 1
    fi

    local local_file="$HOME/.config/opencode/opencode.json"
    local remote_file="~/.config/opencode/opencode.json"
    local remote_target="$1"
    shift
    local -a remote_opts=("$@")

    local -a ssh_cmd=(ssh)
    local -a scp_cmd=(scp)
    if [ ${#remote_opts[@]} -gt 0 ]; then
        ssh_cmd+=("${remote_opts[@]}")
        scp_cmd+=("${remote_opts[@]}")
    fi

    local tmp_source
    local tmp_dest
    local tmp_merged
    tmp_source="$(mktemp)" || return 1
    tmp_dest="$(mktemp)" || {
        rm -f "$tmp_source"
        return 1
    }
    tmp_merged="$(mktemp)" || {
        rm -f "$tmp_source" "$tmp_dest"
        return 1
    }

    if [ "$sync_mode" = "push" ]; then
        if [ ! -f "$local_file" ]; then
            echo "ℹ️  本地缺少 $local_file，跳过 provider 同步"
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return 0
        fi

        if ! "${ssh_cmd[@]}" "$remote_target" "mkdir -p ~/.config/opencode"; then
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return 1
        fi

        if ! "${ssh_cmd[@]}" "$remote_target" "if [ -f ~/.config/opencode/opencode.json ]; then cat ~/.config/opencode/opencode.json; fi" > "$tmp_dest"; then
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return 1
        fi

        # Seed the whole file when the receiver has no config yet; field-level
        # merging only applies once both sides already have opencode.json.
        if [ ! -s "$tmp_dest" ]; then
            if ! "${scp_cmd[@]}" "$local_file" "${remote_target}:${remote_file}"; then
                rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
                return 1
            fi

            echo "Copied full config -> ${remote_target}:${remote_file}"
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return 0
        fi

        _opencode_merge_provider_json "$local_file" "$tmp_dest" "$tmp_merged"
        local merge_status=$?
        if [ $merge_status -eq 3 ]; then
            echo "ℹ️  本地 $local_file 不含 provider，跳过 provider 同步"
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return 0
        fi
        if [ $merge_status -ne 0 ]; then
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return $merge_status
        fi

        if ! "${scp_cmd[@]}" "$tmp_merged" "${remote_target}:${remote_file}"; then
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return 1
        fi

        echo "Synced provider field -> ${remote_target}:${remote_file}"
        rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
        return 0
    fi

    mkdir -p "$HOME/.config/opencode"

    if ! "${ssh_cmd[@]}" "$remote_target" "if [ -f ~/.config/opencode/opencode.json ]; then cat ~/.config/opencode/opencode.json; fi" > "$tmp_source"; then
        rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
        return 1
    fi

    if [ ! -s "$tmp_source" ]; then
        echo "ℹ️  远程缺少 ${remote_file}，跳过 provider 同步"
        rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
        return 0
    fi

    if [ ! -f "$local_file" ]; then
        if ! "${scp_cmd[@]}" "${remote_target}:${remote_file}" "$local_file"; then
            rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
            return 1
        fi
        echo "Copied full config -> $local_file"
        rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
        return 0
    fi

    if [ -f "$local_file" ]; then
        cp "$local_file" "$tmp_dest"
    fi

    _opencode_merge_provider_json "$tmp_source" "$tmp_dest" "$tmp_merged"
    local merge_status=$?
    if [ $merge_status -eq 3 ]; then
        echo "ℹ️  远程 ${remote_file} 不含 provider，跳过 provider 同步"
        rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
        return 0
    fi
    if [ $merge_status -ne 0 ]; then
        rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
        return $merge_status
    fi

    cp "$tmp_merged" "$local_file"
    echo "Synced provider field -> $local_file"
    rm -f "$tmp_source" "$tmp_dest" "$tmp_merged"
}

# Sync OpenCode local config files between machines.
_opencode_sync() {
    local sync_mode="$1"
    shift
    # Plugins are managed as their own git repo and are not part of opencode sync.
    _remote_sync "$sync_mode" "$HOME/.config/opencode/" "~/.config/opencode/" "oh-my-opencode.json" "opencode" "" "$@" || return 1
    _opencode_sync_provider "$sync_mode" "$@" || return 1
}

opencode_push() { _opencode_sync "push" "$@"; }
opencode_pull() { _opencode_sync "pull" "$@"; }
alias opencode-push='opencode_push'
alias opencode-pull='opencode_pull'
# Batch-sync Claude, Codex, and OpenCode configs with one command.
_vibe_sync() {
    local sync_mode="$1"
    shift

    if [ "$sync_mode" != "push" ] && [ "$sync_mode" != "pull" ]; then
        echo "Unknown sync mode: $sync_mode"
        return 1
    fi

    if [ $# -lt 1 ]; then
        echo "Usage: vibe_${sync_mode} <ssh_target> [ssh_opts...]"
        echo "Example: vibe_${sync_mode} user@host -p 2022"
        return 1
    fi

    local sync_func=""
    local sync_label=""
    local -a sync_targets=(
        "claude"
        "codex"
        "opencode"
    )
    local target

    for target in "${sync_targets[@]}"; do
        sync_func="${target}_${sync_mode}"
        sync_label="${target}-${sync_mode}"
        echo "==> ${sync_label}"
        "$sync_func" "$@" || return 1
    done
}

vibe_push() { _vibe_sync "push" "$@"; }
vibe_pull() { _vibe_sync "pull" "$@"; }
alias vibe-push='vibe_push'
alias vibe-pull='vibe_pull'

# When the file is sourced, this returns immediately. When executed via
# `bash bashrc_common.sh ...` or `bash -s -- ...`, it dispatches CLI commands.
dotfile_cli_dispatch_if_executed "$@"
