#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INPUT_FILE="${1:-$ROOT_DIR/src/bashrc_common.dev.sh}"
OUTPUT_FILE="${2:-$ROOT_DIR/bashrc_common.sh}"
SRC_ROOT="$(cd "$(dirname "$INPUT_FILE")" && pwd)"

emit_file() {
  local file="$1"
  local line=""

  while IFS= read -r line || [ -n "$line" ]; do
    if [[ "$line" == '#!/usr/bin/env bash' ]]; then
      continue
    fi

    if [[ "$line" =~ ^DOTFILE_DEV_ROOT= ]]; then
      continue
    fi

    if [[ "$line" =~ ^source[[:space:]]+\"\$DOTFILE_DEV_ROOT/(.+)\"$ ]]; then
      emit_file "$SRC_ROOT/${BASH_REMATCH[1]}"
      continue
    fi

    if [[ "$line" =~ ^source[[:space:]]+\"\$\{DOTFILE_DEV_ROOT\}/(.+)\"$ ]]; then
      emit_file "$SRC_ROOT/${BASH_REMATCH[1]}"
      continue
    fi

    printf '%s\n' "$line"
  done < "$file"
}

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{
  printf '#!/usr/bin/env bash\n\n'
  printf '# This file is generated by scripts/build_bashrc_common.sh.\n'
  printf '# Do not edit it directly; edit files under src/ instead.\n\n'
  emit_file "$INPUT_FILE"
} > "$tmp_file"

mv "$tmp_file" "$OUTPUT_FILE"
chmod 755 "$OUTPUT_FILE"
